"""MAM 全体設定 (config) モジュール"""
from app.config.defaults import (
    BASE_LOAN_RATES,
    MAX_LTV,
    DEFAULT_LTV,
    DEFAULT_TARGET_YIELDS,
    STRESS_RATE_DELTA,
    DSCR_THRESHOLDS,
    PRICE_RATIO_THRESHOLDS,
    RANK_THRESHOLDS,
    EXIT_CAP_RATE_DRIFT,
    IRR_CLAMP,
    REPAIR_COST_BASE_PER_SQM,
    OFFER_RISK_DISCOUNT_RATE,
    OFFER_HIGH_MULTIPLIER,
)

__all__ = [
    "BASE_LOAN_RATES",
    "MAX_LTV",
    "DEFAULT_LTV",
    "DEFAULT_TARGET_YIELDS",
    "STRESS_RATE_DELTA",
    "DSCR_THRESHOLDS",
    "PRICE_RATIO_THRESHOLDS",
    "RANK_THRESHOLDS",
    "EXIT_CAP_RATE_DRIFT",
    "IRR_CLAMP",
    "REPAIR_COST_BASE_PER_SQM",
    "OFFER_RISK_DISCOUNT_RATE",
    "OFFER_HIGH_MULTIPLIER",
]
